default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: db/legado_development
  username: postgres
  password: mysecretpassword
  host: localhost

test:
  <<: *default
  database: db/legado_test
  username: postgres
  password: mysecretpassword
  host: localhost

production:
  <<: *default
  database: db/legado_production
  username: postgres
  password: mysecretpassword
  host: localhost
